'use strict';

/**
 * Secure Share Email OTP Setup
 * Generates OTP_SECRET and writes a clean .env with the fixed project emails.
 * You only paste the Gmail App Password when prompted.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const PROJECT_EMAIL = 'systemsecureshare@gmail.com';
const RECEIVER_EMAIL = 'hassanbadha33@gmail.com';

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(question, (answer) => { rl.close(); resolve(answer.trim()); }));
}

(async () => {
  console.log('\nSecure Share Email OTP Setup');
  console.log('Sender Gmail : ' + PROJECT_EMAIL);
  console.log('Receiver     : ' + RECEIVER_EMAIL);
  console.log('\nPaste the 16-character Gmail App Password. Do not use the normal Gmail password.');

  const appPassword = await ask('Gmail App Password: ');
  if (!appPassword || appPassword.length < 12) {
    console.error('\nSetup stopped: Gmail App Password looks too short.');
    process.exit(1);
  }

  const otpSecret = crypto.randomBytes(32).toString('hex');
  const env = `# Secure Share System environment settings\n# Generated by npm run setup:email\n\nHOST=127.0.0.1\nPORT=3000\n\nOTP_DELIVERY_MODE=email\nADMIN_2FA_TTL_SECONDS=300\nADMIN_2FA_MAX_ATTEMPTS=5\n\nOTP_SECRET=${otpSecret}\n\nSMTP_HOST=smtp.gmail.com\nSMTP_PORT=465\nSMTP_SECURE=true\n\nSMTP_USER=${PROJECT_EMAIL}\nSMTP_PASS=${appPassword.replace(/\r?\n/g, '').trim()}\n\nOTP_FROM="Secure Share <${PROJECT_EMAIL}>"\nOTP_TO_EMAIL=${RECEIVER_EMAIL}\n`;

  fs.writeFileSync(path.join(__dirname, '..', '.env'), env, 'utf8');
  console.log('\nDone. .env has been created successfully.');
  console.log('Next steps:');
  console.log('1. npm install');
  console.log('2. npm run check:email');
  console.log('3. node server.js');
  console.log('Password reset codes will also go to ' + RECEIVER_EMAIL + ' during local demo.');
})();
